services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - API_PORT=5000
      - GEMINI_API_KEY=AIzaSyCwcbiW329Kq2H8ALu-SuOT44FZaWNWjo8
    networks:
      - app-network

networks:
  app-network:
    driver: bridge