version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./spring-docs:/app/static/docs:ro  # Read-only access to docs
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - api
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./spring-docs:/app/docs  # Shared documentation directory
      - ./backend/src:/app/src  # Mount source for development
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    command: python src/serve_docs.py

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./spring-docs:/app/docs  # Shared documentation directory
      - ./backend/src:/app/src  # Mount source for development
    environment:
      - PYTHONUNBUFFERED=1
      - API_PORT=5000
    networks:
      - app-network
    command: python src/api_server.py

  scraper:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./spring-docs:/app/docs  # Shared documentation directory
      - ./backend/src:/app/src  # Mount source for development
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    command: python src/spring_docs_scraper.py
    profiles:
      - scraper  # Only run when explicitly requested

networks:
  app-network:
    driver: bridge

volumes:
  docs-volume: